### ISSUE TITLE
Audio compilation errors with Visual Studio.

### ISSUE THREAD

**Issue by mdsitton** [OpenRhythm/OpenRhythm#22]
```
1>  soundio.cpp
1>C:\Users\Matthew\development\musicgame\src\core\audio\output\soundio.cpp(98): error C2131: expression did not evaluate to a constant
1>  C:\Users\Matthew\development\musicgame\src\core\audio\output\soundio.cpp(98): note: failure was caused by non-constant arguments or reference to a non-constant symbol
1>  C:\Users\Matthew\development\musicgame\src\core\audio\output\soundio.cpp(98): note: see usage of 'byte_count_max'
1>C:\Users\Matthew\development\musicgame\src\core\audio\output\soundio.cpp(110): error C2440: 'initializing': cannot convert from 'int16_t [byte_count_max]' to 'int16_t'
1>  C:\Users\Matthew\development\musicgame\src\core\audio\output\soundio.cpp(110): note: There is no context in which this conversion is possible
```
Basically the audio code is using some non-constant at compile time variable in a c style array and VS is complaining.

**Comment by mdsitton** [comment]
Here are some other issues with the same code after looking through it closer.

SoundIO:
Our wrappers to setup SoundIO would be almost indistinguishable from the native functions by name.

No use of static variables to keep variables constrained to the current compilation unit.

m_logger is set at a global level, and not the module level that it should be as indicated by the name. (Its named with m_ when its not a member variable)

Sample rate bytes per sample and channel count should be stored in some kind of struct, and not set with macros.

Use of NULL instead of nullptr

soundio_* function all having a return value, when they are only ever 0.(using exceptions instead)

Incorrect use of static c-style arrays causing compilation errors. Use a vector or C++ array

Use of C-style casts (please use C++ style casts in the future)

Casts are way way way overused.

There are return values on functions that are defined as void.


Vorbis codec loader:
Uses c functions to open files.
	- includes stdlib.h instead of cstdio.

More functions returning the same return value all the time.

VorbisSong open still returns errors codes yet mixes it with exceptions.

VorbisSong readBuffer still uses error codes?

**Comment by Salamandar** [comment]
Well uh… VS is just stupid then o.O
Oh, I see. It's just one of the OLD compilers complaining about : 

            int16_t data[byte_count_max];
when byte_count_max is not const. Well I can't do otherwise, that's just the way soundIO (and PortAudio) works. I could decide on a "VERY BIG" byte_count_max at compile-time, but that wouldn't be wise.

Line 110 is :

    int16_t sample = data[channel + 2*i];
Can't see the problem here.

**Comment by mdsitton** [comment]
Use a vector then.

**Comment by Salamandar** [comment]
> Our wrappers to setup SoundIO would be almost indistinguishable from the native functions by name.

Hmm, that's a fact. I will change that. 
> No use of static variables to keep variables constrained to the current compilation unit.

What do you mean by that ?
> m_logger is set at a global level, and not the module level that it should be as indicated by the name. (Its named with m_ when its not a member variable)

Well the problem (for now) is that I have some "c-like" functions that should have access to m_logger. I was wondering about writing a singleton class for SoundIO initializer, I think it would be best.

> Sample rate bytes per sample and channel count should be stored in some kind of struct, and not set with macros.

Yep, that's written in a comment (and in my head). It's just that I have to decide how the output parameters will be detected/ decided.
> Use of NULL instead of nullptr

Hm, okay. I did more C than C++ in my life ;)
 
> soundio_* function all having a return value, when they are only ever 0.(using exceptions instead)

Same, that's my "C-way" of doing things. 
> Incorrect use of static c-style arrays causing compilation errors. Use a vector or C++ array

Hum… That's for the buffers. Libvorbis and libsoundIO only accept c style arrays, you know :p 

> Casts are way way way overused.

That's the way sound libs usually work. Char are the "basic" type everyone work with, but you have to cast them to int/float to work with them.

> 
> Vorbis codec loader:
> Uses c functions to open files.

Well I'm working with libvorbis, remember ? A C library. Using C FILEs Can't do otherwise I think.
