### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#31]
I'm really interrested in learning Rust. I'm currently reading on how integrate Rust code in a C++ application.
How do you feel about putting some of this next-gen awesome language in Openrhythm ? Ofc if you're okay I'll document and comment my code as necessary.

**Comment by mdsitton** [comment]
I'd rather not for a few reasons. First we would all just be learning it, and we would likely be mailing bad decisions with how to use the language since we aren't familiar with it. Secondly already most people that I've talked with that were interested in contributing so far either barely know c++ and most actually use java or c#. Adding rust into the mix could limit who can help even further. And finally my main goals are to make things as simple as possible, adding another language Into the build process goes against that.

**Comment by Salamandar** [comment]
That's too bad but I can't disagree with you. Just wanted to know how you felt about that.
