### ISSUE TITLE
OSX Build

### ISSUE THREAD

**Issue by russelldub** [OpenRhythm/OpenRhythm#34]
Having trouble building on OSX:

* cubeb doesn't appear to be set up correctly as a sub-module.
* release_build.sh script has some errors
  * mkdir and rm options arguments at end of arg list instead of beginning
  * rm CMakeCache.txt before cd'ing to build
* With fmt version 3.0.2 and 4.0 build fails on smf.cpp with error:
>/usr/local/include/fmt/format.h:2228:20: error: ambiguous conversion for functional-style cast from 'const ORCore::MidiChannelMessage' to 'MakeValue<fmt::BasicFormatter<char, fmt::ArgFormatter<char> > >'
    Value result = MakeValue<Formatter>(value);

I'm interested in helping develop (possibly, sporadically), and beta-test.

**Comment by mdsitton** [comment]
Hey man sorry for not getting back to you sooner. It's been an extremely busy month for me. I'm going to be working on things this weekend again. Also I'd be happy to have someone helping out occasionally.

I've been meaning to setup cubeb as a submodule instead of through cmake so hopefully I'll get that fixed this weekend. Should be simple enough to fix the fmt error.

Thanks for the issue!

**Comment by mdsitton** [comment]
Ok so the build script and the fmt issues are fixed, but i'm getting some strange issues building cubeb on osx that i used to not get. Like externalproject_add is building cubeb as the wrong archetecture for some stupid reason... And its not picking up on a dependency i'm trying to empose on the external project and ORCore.. So fun times :/

**Comment by mdsitton** [comment]
@russelldub  This should be all fixed now closing.

**Comment by russelldub** [comment]
Thanks for fixing those issues.  I am able to build and run.  Two issues I had to work out to get it to run:
* SoundTouch-C built but was not on my library path at run-time so I had to modify LD_LIBRARY_PATH to get things to run.  There's probably a better way to link things so that's not required.
* I had to read through the source and make some guesses about what "music" files needed to be where (notes.mid and song.ogg).  Was this documented somewhere and I missed it?  Is there some public domain song(s) that could be included in the repo (or linked as a separate archive so you don't have to have binary blobs)?

I can investigate both of those things if you'd like.  Should I file separate issues?

**Comment by mdsitton** [comment]
I haven't quite finished getting soundtouch working(getting really badly corrupted sound on my wip code). So i haven't yet worried about making certain everything work right everywhere. If you want to look into it for me feel free.

Yeah i really should better document some things, I haven't bothered because i consider the current setup very very temp but have been pushing improvements off until i get some sort of ui working.

I could ask around to various people if they have any songs they've created that I can include with the game.

**Comment by mdsitton** [comment]
Also yeah go ahead and make new issues for everything.

**Comment by russelldub** [comment]
OK.  Will do.  I'll also see what I can figure out about linking SoundTouch-C.
